### ISSUE TITLE
convert_document not working

### ISSUE THREAD

**Issue by SwamiPatil** [DS4SD/deepsearch-toolkit#3]
Hello,
When I run this line of code:
```
import deepsearch as ds
documents = ds.convert_document(proj_key = PROJ_KEY, local_file = PATH_DOCS)
```

I get the following error:

--------------------------------------------------------------------------------------
                          Welcome to the DeepSearch Toolkit
--------------------------------------------------------------------------------------
Processing input:   : 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1144.11it/s]
Submitting input:   :   0%|                                                                        | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "toolkit.py", line 27, in <module>
    documents = ds.convert_document(proj_key = PROJ_KEY, local_file = PATH_DOCS)
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/documents/core/main.py", line 48, in convert_document
    process_local_input(cps_proj_key=proj_key, local_file=Path(local_file))
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/documents/core/input_process.py", line 37, in process_local_input
    task_ids = send_files_for_conversion(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/documents/core/convert.py", line 195, in send_files_for_conversion
    private_download_url = upload_single_file(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/documents/core/convert.py", line 281, in upload_single_file
    api = CpsApi.default_from_env()
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/client/api.py", line 114, in default_from_env
    config = DeepSearchConfig.parse_file(config_file_path())
  File "pydantic/main.py", line 556, in pydantic.main.BaseModel.parse_file
  File "pydantic/parse.py", line 57, in pydantic.parse.load_file
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/pathlib.py", line 1229, in read_bytes
    with self.open(mode='rb') as f:
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/swamipatil/Library/Application Support/DeepSearch/deepsearch_toolkit.json'

**Comment by dolfim-ibm** [comment]
I think you are missing the authentication, try running `deepsearch login` as described here https://ds4sd.github.io/deepsearch-toolkit/getting_started/authentication/

We are now preparing a complete A-Z example for document conversion (not just snippets).

**Comment by SwamiPatil** [comment]
@dolfim-ibm 

Thanks. After running this code,

```
import deepsearch as ds

# API key authorization
auth = ds.DeepSearchKeyAuth(
    username="USER-EMAIL",
    api_key="API-KEY",
)
# In case you have already a valid temporary access_token
# auth = DeepSearchAuth(bearer_token="TOKEN")

config = ds.DeepSearchConfig(
    host="https://deepsearch-experience.res.ibm.com",
    auth=auth,
)

client = ds.CpsApiClient(config)
api = ds.CpsApi(client)
```

I am getting this issue:
Traceback (most recent call last):
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fda20ff2af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "toolkit.py", line 21, in <module>
    client = ds.CpsApiClient(config)
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/client/api.py", line 30, in __init__
    bearer_token=self._authenticate_with_api_key(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/client/api.py", line 81, in _authenticate_with_api_key
    access_token = api.get_access_token(options={"admin": False}).access_token
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/api/users_api.py", line 167, in get_access_token
    return self.get_access_token_with_http_info(**kwargs)  # noqa: E501
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/api/users_api.py", line 242, in get_access_token_with_http_info
    return self.api_client.call_api(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/api_client.py", line 407, in request
    return self.rest_client.POST(url,
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/deepsearch/cps/apis/user/rest.py", line 163, in request
    r = self.pool_manager.request(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/swamipatil/opt/anaconda3/envs/python_38/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='deepsearch-experience.res.ibm.com', port=443): Max retries exceeded with url: /api/cps/user/v1/user/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fda20ff2af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by SwamiPatil** [comment]
Not getting this error after authentication
